apiVersion: v1
kind: Pod
metadata:
  name: etcd 
  labels:
    name: etcd
spec:
  containers:
  - name: etcd 
    image: ishan007/etcd_image
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 2379
  - name: backup-restore 
    image: ishan007/etcdbr_image
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 8080