apiVersion: v1
kind: Pod
metadata: 
  name: etcd
  namespace: dev
  labels:
      type: etcd-dev
spec:
  containers:
    - name: etcd
      image: ishan007/etcd_image
    - name: backup-restore
      image: ishan007/etcdbr_image