apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-sts
  labels:
    type: etcd-backup-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      type: etcd-dev
  template:
    metadata:  
      name: etcd
      namespace: dev
      labels:
          type: etcd-dev
    spec:
      containers:
        - name: etcd
          image: ishan007/etcd_image
        - name: backup-restore
          image: ishan007/etcdbr_image
  serviceName: etcd-h #name of headless service
      