apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  namespace: dev
spec:
  ports:
    - port: 2379
  selector:
    type: etcd-dev
  clusterIP: None

---

apiVersion: v1
kind: Pod
metadata: 
  name: etcd
  namespace: dev
  labels:
      type: etcd-dev
spec:
  containers:
    - name: etcd
      image: ishan007/etcd_image
    - name: backup-restore
      image: ishan007/etcdbr_image
  subdomain: etcd-headless # name of headless Service
  hostname: etcd #Pod name

# for the statefulset you don't need to define the subdomain and hostname, statefulset understand it by itself.

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-sts
  labels:
    type: etcd-backup-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      type: etcd-dev
  template:
    metadata:  
      name: etcd
      namespace: dev
      labels:
          type: etcd-dev
    spec:
      containers:
        - name: etcd
          image: ishan007/etcd_image
        - name: backup-restore
          image: ishan007/etcdbr_image
  serviceName: etcd-headless
      
---

