apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: dev
  labels: 
    type: etcd-dev
spec:
  containers:
    - name: etcd
      image: ishan007/etcd_image
      readinessProbe:
        httpGet:
          path: /health
          port: 2379
    - name: etcd-br
      image: ishan007/etcdbr_image
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
