# livenessProbe: to check whether the application inside the container is running as expected or not.

apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: dev
  labels: 
    type: etcd-dev
spec:
  containers:
    - name: etcd
      image: ishan007/etcd_image
      livenessProbe:
        exec:
          command:
          - /bin/sh
          - -ec
          - ETCDCTL_API=3
          - etcdctl
          - get
          - foo