apiVersion: v1
kind: ConfigMap
metadata:
  name: config-file
  namespace: dev
data:
  #<key>: <value>
  INITIAL_CLUSTER_STATE: "new"
  etcd.conf.yaml: |-
    # Human-readable name for this member.
    name: etcd-test

    # Path to the data directory.
    data-dir: /var/etcd/data/new.etcd

    # Number of committed transactions to trigger a snapshot to disk.
    snapshot-count: 75000

    # Accept etcd V2 client requests
    enable-v2: false

---

apiVersion: v1
kind: Pod
metadata:
  name: etcd-config-test
  namespace: dev
spec:
  containers:
    - name: etcd
      image: ishan007/etcd_image
      volumeMounts:
        - name: etcd-config-file
          mountPath: /var/etcd/config
  volumes:
    - name: etcd-config-file
      configMap:
        name: config-file #<name of config map>
        items:
          - key: etcd.conf.yaml
            path: etcd.conf.yaml


