apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deploy
  labels:
    type: etcd-backup-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: etcd-dev
  template:
    metadata:  
      name: etcd
      namespace: dev
      labels:
          type: etcd-dev
    spec:
      containers:
        - name: etcd
          image: ishan007/etcd_image
        - name: backup-restore
          image: ishan007/etcdbr_image