apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deployment
  labels:
    app: etcd-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etcd-dev
  template:
    metadata:
      name: etcd
      labels:
        app: etcd-dev
    spec:
      containers:
      - name: etcd 
        image: ishan007/etcd_image
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
          - containerPort: 2379
      - name: backup-restore 
        image: ishan007/etcdbr_image
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
          - containerPort: 8080
