apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: dev
  labels:
    type: etcd-service
spec:
  type: ClusterIP
  ports:
    - port: 2379 # it is the port where etcd-service is exposed.
      targetPort: 2379 # it is the port where etcd Pods is exposed.
  selector:
    type: etcd-dev
