apiVersion: v1
kind: Pod
metadata:
  name: etcd
  labels:
    type: etcd-dev
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size # another-node-label-key
            operator: In # operator: NotIn also possible
            values:
            - Large # another-node-label-value
            - Medium # another-node-label-value
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: <another-node-label-key>
              operator: In
              values:
              - <another-node-label-value>
  containers:
  - name: etcd
    image: ishan007/etcd_image


# But node affinity makes it possible to use the annotations in the expressions. 
# Anti-affinity ensures that the pod doesn’t get scheduled a node that matches the rule.