apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  #volume is not limited to namespace, it is available to all namespaces, hence is cluster scoped
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/data"

