apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: dev
  labels:
    type: my-dev
spec:
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-claim
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
