apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  selector:
    app: etcd
  ports:
    # Kubernetes lets you configure multiple port definitions on a Service object.
    # When using multiple ports for a Service, you must give all of your ports names so that these are unambiguous.
  - name: client
    port: 2379
    protocol: TCP
    targetPort: client
  - name: peer
    port: 2380
    protocol: TCP
    targetPort: peer

---

apiVersion: v1
kind: Service
metadata:
  name: etcd-lb
  labels:
    app: etcd
spec:
  type: LoadBalancer
  selector:
    app: etcd
  ports:
   - port: 2379
     protocol: TCP
     targetPort: 2379

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
type: Opaque
data:
  accessKeyID: ""
  region: ""
  secretAccessKey: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-cm
  labels:
    app: etcd
data:
  INITIAL_CLUSTER: "etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380,etcd-3=http://etcd-3.etcd:2380,etcd-4=http://etcd-4.etcd:2380"
  INITIAL_CLUSTER_STATE: "new"
  INITIAL_CLUSTER_TOKEN: "token-01"
  start.sh: |-
    #!/bin/sh
    echo "${INITIAL_CLUSTER}"
    etcd --data-dir /data/data.etcd \
      --name ${POD_NAME} \
      --initial-advertise-peer-urls=http://${POD_NAME}.etcd:2380 \
      --listen-peer-urls=http://0.0.0.0:2380 \
      --advertise-client-urls=http://${POD_NAME}.etcd:2379 \
      --listen-client-urls=http://0.0.0.0:2379 \
      --initial-cluster=${INITIAL_CLUSTER} \
      --initial-cluster-state=${INITIAL_CLUSTER_STATE} \
      --initial-cluster-token=${INITIAL_CLUSTER_TOKEN} \
      --max-snapshots=0 \
      --max-wals=0

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  replicas: 5
  serviceName: etcd
  selector:
    matchLabels:
      app: etcd
  #podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: etcd
    spec:
      serviceAccountName: lease-service-account
      containers:
      - name: backup-restore
        image: eu.gcr.io/gardener-project/gardener/etcdbrctl:v0.14.0-dev-b0111bc56f762311f597d091045df74164b7330b
        command:
        - etcdbrctl
        - server
        - --schedule=0 */1 * * *
        - --max-backups=7
        - --defragmentation-schedule=*/9 * * * *
        - --storage-provider=S3
        - --store-prefix=etcd-main
        - --compress-snapshots=true
        - --compression-policy=gzip
        - --enable-snapshot-lease-renewal=false 
        - --enable-member-lease-renewal=false 
        - --full-snapshot-lease-name=full-snap-lease
        - --delta-snapshot-lease-name=delta-snap-lease
        env: 
        - name: STORAGE_CONTAINER
          value: "ishan-etcdbr-test-bucket"
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: "region"
              name: etcd-backup
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: "secretAccessKey"
              name: etcd-backup
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: "accessKeyID"
              name: etcd-backup
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
      - name: etcd
        image: bitnami/etcd:3
        imagePullPolicy: IfNotPresent
        command:
        - /scripts/start.sh
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -ec
        #     - ETCDCTL_API=3
        #     - etcdctl
        #     - --endpoints=http://${POD_NAME}.etcd:2379
        #     - get
        #     - foo
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 2379
        #   initialDelaySeconds: 60
        #   periodSeconds: 5
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.podIP"
        - name: INITIAL_CLUSTER
          valueFrom:
            configMapKeyRef:
              key: "INITIAL_CLUSTER"
              name: etcd-cm 
        - name: INITIAL_CLUSTER_STATE
          valueFrom:
            configMapKeyRef:
              key: "INITIAL_CLUSTER_STATE"
              name: etcd-cm
        - name: INITIAL_CLUSTER_TOKEN
          valueFrom:
            configMapKeyRef:
              key: "INITIAL_CLUSTER_TOKEN"
              name: etcd-cm
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: peer
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: "/data"
        - name: etcd-start-script
          mountPath: "/scripts"
      volumes:
      - name: data
        emptyDir: {}
      - name: etcd-start-script
        configMap:
          name: etcd-cm
          defaultMode: 0755
          items:
          - key: start.sh
            path: start.sh
